# Generated by Django 4.2.9 on 2024-02-04 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=600)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.proyecto')),
            ],
        ),
    ]
