# Generated by Django 4.2.9 on 2024-02-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tile',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='task',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
